# Generated by Django 5.1.2 on 2024-11-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_see',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.dataset')),
            ],
        ),
    ]
