# Generated by Django 5.1.2 on 2024-10-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10000)),
                ('amg', models.ImageField(upload_to='')),
                ('data', models.CharField(blank=True, default='not load yet', max_length=1000000000000000000000000000000000, null=True)),
                ('come_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000000000000000000)),
                ('email', models.EmailField(max_length=1000000000000000)),
                ('tik', models.CharField(default='what you want to ask ', max_length=111111111888888888888888888888888888888888888888888888888888888888888)),
                ('answers', models.CharField(blank=True, default='not check from the admin ', max_length=10000000000000, null=True)),
            ],
        ),
    ]
