# Generated by Django 5.1.2 on 2024-10-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tik',
            name='tik',
            field=models.CharField(max_length=11111111188888888888888888888888888888888888888888888888888888888888),
        ),
    ]
