# Generated by Django 5.1.2 on 2024-10-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_tik_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='amg',
            new_name='img',
        ),
    ]
