# Generated by Django 5.1.2 on 2024-10-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_tik_tik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tik',
            name='answers',
            field=models.CharField(max_length=10000000000000),
        ),
    ]
