# Generated by Django 5.1.2 on 2024-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_amg_data_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='chtik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000000000000000000)),
                ('timecheck', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tik',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tik',
            name='timeuploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
