# Generated by Django 5.1.2 on 2024-10-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_chtik_tik_answered_tik_timeuploaded'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chtik',
            new_name='checktik',
        ),
    ]
