# Generated by Django 5.1.2 on 2024-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_rename_chtik_checktik'),
    ]

    operations = [
        migrations.AddField(
            model_name='tik',
            name='topic',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
    ]
