# Generated by Django 5.1.2 on 2024-10-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_tik_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tik',
            new_name='tikmodel',
        ),
    ]
