# Generated by Django 5.1.2 on 2024-10-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_tikmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktik',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.checktik'),
        ),
        migrations.CreateModel(
            name='fileinput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(blank=True, max_length=10000000000000000000, null=True)),
                ('data', models.FileField(blank=True, null=True, upload_to='files')),
                ('timeuploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.data')),
            ],
        ),
        migrations.CreateModel(
            name='imginput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('name', models.CharField(blank=True, max_length=10000000000000000000, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='img')),
                ('timeuploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.data')),
            ],
        ),
    ]
