# Generated by Django 5.1.2 on 2024-10-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_checktik_user_fileinput_imginput'),
    ]

    operations = [
        migrations.AddField(
            model_name='tikmodel',
            name='ticket_link',
            field=models.IntegerField(blank=True, max_length=10000000000000, null=True),
        ),
    ]
